### PR TITLE
Added feature for inline STDIN of JSON string

### PR DESCRIPTION
**Pull request by jdgiotta**
Need some input here. Usage or help output needs some critique.

### CODE REVIEW

**Comment by jdgiotta** [comment]
The way it works is that if you do not pass the `-f` flag for a input file you can enter a trailing string for STDIN. For example,

`_LAMBDA_SERVER_PORT=10101 bin/run-go-lambda "{ \"company\": \"GOOG\", \"user\": \"109121\" }"`

**Comment by joffotron** [comment]
Ah, I tried it out and was a little confused!

What I meant in https://github.com/raisebook/run-go-lambda/issues/1 was that it would literally read input from stdin (not the first argument), e.g.:

`cat test.json | ./run-lambda-go` 

or 

`./run-lambda-go < test.json`

This would let you chain the command more easily, as is the *nix way

**Comment by jdgiotta** [comment]
Ah, I gotcha. Sorry for the confusion. That should not be too difficult to accommodate.

**Comment by jdgiotta** [comment]
@joffotron I added the expected feature.

Example:

`_LAMBDA_SERVER_PORT=10101 AWS_LAMBDA_FUNCTION_NAME=data_monster bin/run-go-lambda -t 300 < event_payload_example.json`

_or_

`cat event_payload_example.json | _LAMBDA_SERVER_PORT=10101 AWS_LAMBDA_FUNCTION_NAME=data_monster bin/run-go-lambda -t 300`

_or_

` _LAMBDA_SERVER_PORT=10101 AWS_LAMBDA_FUNCTION_NAME=data_monster bin/run-go-lambda -t 300 -f event_payload_example.json`

**Review by joffotron — APPROVED** [review]
Thanks for your changes! Just did a bit of a cleanup, but all good to merge 👍

**Pull request merged**
